name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    plan:
        name: Plan (PR checks)
        runs-on: ubuntu-latest

        if: github.event_name == 'pull_request'
        steps:
        - uses: actions/checkout@v4
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.5.0
        - name: Terraform fmt
          run: terraform -chdir=terraform fmt -check
        - name: Initialize Terraform
          run: terraform -chdir= terraforminit -input=false

        - name: Validate Terraform configuration
          run: terraform -chdir=terraform validate

        - name: Run tfsec
          uses: aquasecurity/tfsec-action@v1
        - name: Terraform plan
          run: terraform -chdir=terraform plan -out=tfplan -input=false
        - name: Upload plan for PR
          uses: actions/upload-artifact@v4
          with:
            name: tfplan 
            path: terraform/tfplan

    apply:
        name: Apply (protected branch)
        needs: plan
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        environment:
          name: production
          url: https://example.com
        steps:
        - uses: actions/checkout@v4
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
          with:
                terraform_version: 1.5.0
        - name: Download plan
          uses: actions/download-artifact@v4
          with:
                name: tfplan
        - name: Terraform apply
          run: terraform -chdir=terraform apply -input=false tfplan


          